server:
  port: 8080
  servlet:
    context-path: /
  tomcat:

    max-threads: 6

    min-spare-threads: 3

    accept-count: 10

    max-connections: 1000
spring:
  datasource:
    url:  jdbc:mysql://localhost:3306/weixindb?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456789

  thymeleaf:
    prefix: classpath:/templates/
    mode: HTML
    encoding: UTF-8
    cache: false
    suffix: .html

mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
